version: 2.1

jobs:
  test-build-and-tag: 
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          name: unitests
          command: python src/tests.py
      - run: echo "This is tag << pipeline.git.tag >>" 
      - run:
          name: Build image and Push image to Docker Hub
          # TAG=0.1.$CIRCLE_BUILD_NUM
          command: |
            TAG=<< pipeline.git.tag >>
            docker build -t alexleethinker/version_control_demo:$TAG .
            echo lz8674168 | docker login -u alexleethinker --password-stdin
            docker push alexleethinker/version_control_demo:$TAG
workflows:
  project-deploy-workflows: 
    jobs:
      - test-build-and-tag:
          filters: 
            tags:
              only: 
                - /^v.*/
            branches:
                ignore: /.*/