version: 2.1

jobs:
  test-build-and-tag: 
    docker:
      - image: cimg/python:3.12.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: unitests
          command: python src/tests.py
      # - run: echo "This is tag << pipeline.git.tag >>" 
      - run:
          name: Build image and Push image to Docker Hub
          # TAG=0.1.$CIRCLE_BUILD_NUM
          command: |
            TAG=<< pipeline.git.tag >>
            docker build -t $DOCKERHUB_USERNAME/version_control_demo:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/version_control_demo:$TAG
workflows:
  project-deploy-workflows: 
    jobs:
      - test-build-and-tag:
          filters: 
            tags:
              only: 
                - /^v.*/