version: 2.1

jobs:
  test-build-and-tag: 
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: unitests
          command: python tests.py
      - run:
          name: Build image and Push image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/VersionControlDemo:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/VersionControlDemo:$TAG
workflows:
  Step: 
    jobs:
      - test-build-and-tag